# Generated by Django 3.1.1 on 2021-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_img', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('message_title', models.CharField(max_length=100)),
                ('message_description', models.TextField()),
                ('message_description_1st', models.TextField(blank=True)),
                ('message_description_2nd', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(upload_to='photo/%Y/%m/%d')),
            ],
        ),
    ]
