# Generated by Django 3.1.7 on 2021-05-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210530_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
