# Generated by Django 3.1.1 on 2021-05-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210530_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_up_heading', models.CharField(max_length=200)),
                ('pop_up_img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('button_name', models.CharField(max_length=200)),
            ],
        ),
    ]
