# Generated by Django 3.1.1 on 2021-05-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('hover_profile_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_descriptions', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
