# Generated by Django 3.1.1 on 2021-05-29 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=700)),
                ('blog_tag', models.CharField(max_length=400)),
                ('blog_image', models.ImageField(max_length=500, upload_to='photos/%Y/%m/%d')),
                ('blog_describe', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
