# Generated by Django 3.1.1 on 2021-06-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image_name', models.CharField(max_length=200)),
                ('slider_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('slider_image_title', models.CharField(max_length=100)),
                ('slider_image_description', models.TextField()),
                ('slider_image_button_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_up_heading', models.CharField(max_length=200)),
                ('pop_up_img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('button_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=200)),
                ('reviewer_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('reviewer_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UniversityLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=400)),
                ('university_logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
