# Generated by Django 3.1.7 on 2021-05-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=400)),
                ('university_logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
