# Generated by Django 3.1.7 on 2021-05-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_universitylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=200)),
                ('reviewer_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('reviewer_description', models.TextField()),
            ],
        ),
    ]
