# Generated by Django 3.1.7 on 2021-05-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_title', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('service_description', models.TextField()),
                ('service_img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
