# Generated by Django 3.1.7 on 2021-05-30 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
