# Generated by Django 3.1.7 on 2021-05-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210530_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(max_length=300),
        ),
    ]
