# Generated by Django 3.1.7 on 2021-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_delete_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='slider_image_button_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='slider_image_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='slider_image_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
