# Generated by Django 3.1.1 on 2021-05-30 04:56

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('qualification', models.CharField(max_length=20)),
                ('course_completed', models.CharField(max_length=20)),
                ('GPA', models.CharField(max_length=20)),
                ('institution_name', models.CharField(max_length=200)),
                ('parents_Name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('courses', models.CharField(max_length=100)),
                ('scores', models.CharField(max_length=20)),
                ('planning_to_take_test', models.CharField(max_length=200)),
                ('where_to_study', models.CharField(max_length=100)),
                ('preferred_course', models.CharField(max_length=200)),
                ('preferred_uni', models.CharField(max_length=200)),
                ('declare_to_use_information', models.CharField(max_length=100)),
                ('can_use_details', models.CharField(max_length=20)),
                ('consult_date', models.DateField(max_length=200)),
                ('how_do_you_know_us', models.CharField(max_length=200)),
            ],
        ),
    ]
