# Generated by Django 3.1.7 on 2021-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=300)),
                ('service_description', models.TextField()),
                ('service_img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
