# Generated by Django 3.1.7 on 2021-05-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visafacts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisaDetail',
        ),
    ]
