# Generated by Django 3.1.7 on 2021-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visafacts', '0002_delete_visadetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_title', models.CharField(blank=True, max_length=400)),
                ('visa_img', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('visa_detail', models.TextField(blank=True)),
                ('visa_2nd_title', models.CharField(blank=True, max_length=400)),
                ('visa_2nd_detail', models.TextField(blank=True)),
            ],
        ),
    ]
