# Generated by Django 3.1.1 on 2021-05-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300)),
                ('teacher_name', models.CharField(max_length=100)),
                ('course_start_date', models.DateField()),
                ('course_description', models.TextField(max_length=200)),
                ('course_button_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_img', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('hero_title', models.CharField(max_length=300)),
                ('hero_slogan', models.CharField(max_length=300)),
                ('hero_subject_name', models.CharField(max_length=100)),
                ('hero_subject_name_I', models.CharField(max_length=100)),
                ('hero_button_name', models.CharField(max_length=100)),
            ],
        ),
    ]
