# Generated by Django 3.1.1 on 2021-05-28 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
